import { ThemeColors, ThemeContext } from '@/components/ThemeContext';
import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Print from 'expo-print';
import { useFocusEffect } from 'expo-router';
import * as Sharing from 'expo-sharing';
import React, { useCallback, useContext, useState } from 'react';
import { Alert, FlatList, Image, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import ImageViewing from "react-native-image-viewing"; // Reuse the zoom viewer
import { SafeAreaView } from 'react-native-safe-area-context';

export default function HistoryScreen() {
  const { isDark } = useContext(ThemeContext);
  const theme = isDark ? ThemeColors.dark : ThemeColors.light;
  const styles = getStyles(theme, isDark);

  const [history, setHistory] = useState<any[]>([]);
  
  // --- NEW STATE FOR REPORT VIEWING ---
  const [selectedReport, setSelectedReport] = useState<any>(null);
  const [modalVisible, setModalVisible] = useState(false);
  const [zoomVisible, setZoomVisible] = useState(false);

  useFocusEffect(
    useCallback(() => {
      loadHistory();
    }, [])
  );

  const loadHistory = async () => {
    try {
      const stored = await AsyncStorage.getItem('scan_history');
      if (stored) setHistory(JSON.parse(stored));
    } catch (e) {
      console.error(e);
    }
  };

  const clearHistory = async () => {
    Alert.alert(
      "Clear History",
      "Are you sure you want to delete all saved scans?",
      [
        { text: "Cancel", style: "cancel" },
        { 
          text: "Delete", 
          style: "destructive", 
          onPress: async () => {
            await AsyncStorage.removeItem('scan_history');
            setHistory([]);
          }
        }
      ]
    );
  };

  // --- NEW: PDF LOGIC (Reused for History Items) ---
  const generatePDF = async () => {
    if (!selectedReport) return;
    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; }
            h1 { color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 10px; }
            .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
            .patient-info { background: #f4f6f8; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
            .scan-img { width: 100%; max-height: 400px; object-fit: contain; border: 1px solid #ddd; margin-bottom: 20px; }
            table { width: 100%; border-collapse: collapse; }
            th { text-align: left; background: #eee; padding: 10px; }
            td { padding: 10px; border-bottom: 1px solid #eee; }
            .high-risk { color: red; font-weight: bold; }
            .footer { margin-top: 50px; font-size: 12px; color: #666; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <div><h2 style="margin:0;">MedTriage General Hospital</h2><p style="margin:5px 0; color:#666;">Radiology Department</p></div>
            <div style="text-align:right;"><p><strong>Date:</strong> ${selectedReport.analysisDate}</p></div>
          </div>
          <div class="patient-info">
            <p><strong>Patient Name:</strong> ${selectedReport.patientName}</p>
            <p><strong>Scan Type:</strong> Chest X-Ray (PA View)</p>
          </div>
          <h1>AI Analysis Report</h1>
          <img src="${selectedReport.imageBase64}" class="scan-img" />
          <h3>Detailed Findings</h3>
          <table>
            <tr><th>Condition</th><th>Probability Score</th><th>Status</th></tr>
            ${selectedReport.findings.map((f: any) => `
              <tr>
                <td>${f.name}</td>
                <td>${f.score.toFixed(1)}%</td>
                <td class="${f.score > 50 ? 'high-risk' : ''}">${f.score > 50 ? 'DETECTED' : 'Normal'}</td>
              </tr>
            `).join('')}
          </table>
          <div class="footer"><p>Generated by MedTriage AI System.</p></div>
        </body>
      </html>
    `;
    try {
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri);
    } catch (error) { Alert.alert("Error", "Could not generate PDF"); }
  };

  const openReport = (item: any) => {
    setSelectedReport(item);
    setModalVisible(true);
  };

  const renderItem = ({ item }: { item: any }) => (
    <TouchableOpacity onPress={() => openReport(item)} activeOpacity={0.7}>
      <View style={styles.card}>
        <Image source={{ uri: item.imageBase64 }} style={styles.thumbnail} />
        <View style={{ flex: 1, paddingHorizontal: 15 }}>
          <Text style={styles.patientName}>{item.patientName}</Text>
          <Text style={styles.date}>{item.analysisDate}</Text>
          <Text style={{ fontSize: 12, color: theme.subText, marginTop: 4 }}>
            {item.findings[0].name} ({item.findings[0].score.toFixed(0)}%)
          </Text>
        </View>
        <View style={[styles.badge, { backgroundColor: item.findings[0].score > 50 ? theme.danger : theme.success }]}>
          <Text style={styles.badgeText}>{item.findings[0].score > 50 ? 'HIGH' : 'LOW'}</Text>
        </View>
      </View>
    </TouchableOpacity>
  );

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.headerRow}>
        <Text style={styles.header}>Recent Scans</Text>
        <TouchableOpacity onPress={clearHistory}>
          <Ionicons name="trash-outline" size={24} color={theme.danger} />
        </TouchableOpacity>
      </View>

      {history.length === 0 ? (
        <View style={styles.emptyState}>
          <Ionicons name="medical-outline" size={60} color={theme.border} />
          <Text style={{ color: theme.subText, marginTop: 20 }}>No scans recorded yet.</Text>
        </View>
      ) : (
        <FlatList
          data={history}
          keyExtractor={(item) => item.id}
          renderItem={renderItem}
          contentContainerStyle={{ paddingBottom: 20 }}
        />
      )}

      {/* --- REPORT DETAIL MODAL --- */}
      <Modal animationType="slide" visible={modalVisible} onRequestClose={() => setModalVisible(false)} presentationStyle="pageSheet">
        {selectedReport && (
          <View style={styles.modalContainer}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Medical Report</Text>
              <TouchableOpacity onPress={() => setModalVisible(false)}>
                <Ionicons name="close-circle" size={30} color={theme.subText} />
              </TouchableOpacity>
            </View>

            <ScrollView contentContainerStyle={{padding: 20}}>
              {/* Image with Zoom */}
              <TouchableOpacity onPress={() => setZoomVisible(true)} activeOpacity={0.9}>
                <Image source={{ uri: selectedReport.imageBase64 }} style={styles.detailImage} resizeMode="contain" />
                <View style={styles.zoomOverlay}><Text style={{ color: 'white', fontSize: 20 }}>🔍</Text></View>
              </TouchableOpacity>

              {/* Patient Info */}
              <View style={styles.infoBox}>
                <View style={styles.infoRow}>
                  <Text style={styles.label}>Patient:</Text>
                  <Text style={styles.value}>{selectedReport.patientName}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.label}>Date:</Text>
                  <Text style={styles.value}>{selectedReport.analysisDate}</Text>
                </View>
              </View>

              {/* Findings */}
              <Text style={styles.sectionHeader}>Detailed Findings</Text>
              {selectedReport.findings.map((f: any, i: number) => (
                <View key={i} style={styles.findingRow}>
                  <Text style={styles.findingName}>{f.name}</Text>
                  <View style={styles.progressContainer}>
                     <View style={{ 
                       height: '100%', borderRadius: 4, 
                       width: `${f.score}%`, 
                       backgroundColor: f.score > 50 ? theme.danger : theme.success 
                     }} />
                  </View>
                  <Text style={styles.score}>{f.score.toFixed(1)}%</Text>
                </View>
              ))}

              <TouchableOpacity style={styles.pdfButton} onPress={generatePDF}>
                <Text style={styles.pdfButtonText}>📄 Reshare PDF Report</Text>
              </TouchableOpacity>
            </ScrollView>
          </View>
        )}
      </Modal>

      {/* ZOOM VIEWER */}
      {selectedReport && (
        <ImageViewing 
          images={[{ uri: selectedReport.imageBase64 }]} 
          imageIndex={0} 
          visible={zoomVisible} 
          onRequestClose={() => setZoomVisible(false)} 
        />
      )}
    </SafeAreaView>
  );
}

const getStyles = (theme: typeof ThemeColors.light, isDark: boolean) => StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.background, padding: 20 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  header: { fontSize: 28, fontWeight: '800', color: theme.primary },
  
  card: { 
    flexDirection: 'row', alignItems: 'center', backgroundColor: theme.card, 
    padding: 15, borderRadius: 12, marginBottom: 15,
    shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 
  },
  thumbnail: { width: 60, height: 60, borderRadius: 8, backgroundColor: '#eee' },
  patientName: { fontSize: 16, fontWeight: 'bold', color: theme.text },
  date: { fontSize: 12, color: theme.subText },
  badge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8 },
  badgeText: { color: 'white', fontSize: 10, fontWeight: 'bold' },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 100 },

  // Modal Styles
  modalContainer: { flex: 1, backgroundColor: theme.background },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderColor: theme.border },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: theme.text },
  
  detailImage: { width: '100%', height: 250, backgroundColor: 'black', borderRadius: 12 },
  zoomOverlay: { position: 'absolute', top: 10, right: 10, backgroundColor: 'rgba(0,0,0,0.6)', width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  
  infoBox: { backgroundColor: theme.card, padding: 15, borderRadius: 12, marginTop: 20, borderWidth: 1, borderColor: theme.border },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  label: { color: theme.subText, fontWeight: 'bold' },
  value: { color: theme.text },

  sectionHeader: { fontSize: 18, fontWeight: 'bold', color: theme.text, marginTop: 25, marginBottom: 15 },
  findingRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  findingName: { width: 120, color: theme.text, fontSize: 14 },
  progressContainer: { flex: 1, height: 8, backgroundColor: theme.border, borderRadius: 4, marginHorizontal: 10 },
  score: { width: 50, textAlign: 'right', fontWeight: 'bold', color: theme.subText },

  pdfButton: { backgroundColor: theme.primary, padding: 15, borderRadius: 12, alignItems: 'center', marginTop: 40, marginBottom: 40 },
  pdfButtonText: { color: 'white', fontWeight: 'bold', fontSize: 16 }
});